version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-todo-app"
s3_prefix = "sam-todo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hniiozy06797"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
image_repositories = []
